### ISSUE TITLE
Start/End Date field

### ISSUE THREAD

**Issue by benjec83** [deejay-hub/timeline-lwc#203] opened 2022-07-25 00:32 UTC
**Describe the solution you'd like**
I was wondering if it would be possible to add the option for a start/end date so you have the option to span an item over a time frame

Example - If I wanted to show out of office dates to look for gaps in coverage, having a start and end date would allow to see the whole time that person was out

**Comment by deejay-hub** [comment] 2022-07-25 03:00
Hi @benjec83. This looks like a duplicate of https://github.com/deejay-hub/timeline-lwc/issues/107. We have merged some community pull requests into the procyon branch in this repo if you want to look at the early proposed code to support spans between dates. So, in short, we are looking into it.

**Closed by deejay-hub** 2022-07-25 03:00 UTC
Labels: duplicate
